### ISSUE TITLE
agreements support

### ISSUE THREAD

**Issue by redwolfairsoft** [airwallex/paymentacceptance-plugin-magento#47]
Hi Developer

https://github.com/airwallex/paymentacceptance-plugin-magento/assets/138568447/250bc792-bbdb-43ef-82ce-7e7cd4556d8e

I am using demo airwallex account. After checkout, it keep saying "The order wasn't placed. First, agree to the terms and conditions, then try placing your order again". As you can see in the video, I have selected terms and conditions checkbox. Any ideas here? Thanks.

Best regards
Redwolf Airsoft

**Comment by leon-zhang-awx** [comment]
Sorry for the late reply. We didn't support the agreement before. Now we have added it. Please upgrade it.
