### ISSUE TITLE
Customize google, apple pay buttons

### ISSUE THREAD

**Issue by hoangvh94** [airwallex/paymentacceptance-plugin-magento#50]
How can I customize these button? Size, color, label ?

**Comment by leon-zhang-awx** [comment]
<img width="351" alt="image" src="https://github.com/user-attachments/assets/d115e39d-fd69-444d-a588-693773f0e6a6">
<img width="761" alt="image" src="https://github.com/user-attachments/assets/31e150e2-6e53-46bc-85d4-903e31f96b93">

Hi, we can only change color and label now.
